import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";
import { Toaster } from "sonner";
import { FormProvider } from "./context/FormContext";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Feature Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased ${montserrat.variable}`}>
      <FormProvider>
        <Header/>
        {children}
        <Toaster richColors position="top-center" />
        <Footer/>
        </FormProvider>
      </body>
    </html>
  );
}
