import "./globals.css";
import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import Header from "./components/layout/header";
import Footer from "./components/layout/footer";
import { Toaster } from "sonner";
import { FormProvider } from "./context/FormContext";
import { cn } from "@/app/lib/utils";

const montserrat = Montserrat({
  variable: "--font-montserrat",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Feature Catalog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased" ,montserrat.variable)}>
      <FormProvider>
        <Header/>
        <main>
        {children}
        </main>
        <Toaster richColors position="top-center" />
        <Footer/>
        </FormProvider>
      </body>
    </html>
  );
}
